### ISSUE TITLE
如何使用呢

### ISSUE THREAD

**Issue by jkl2323** [ykrank/AlipayXposed#5]
我加载进xposed框架 打开支付宝账单页面没有效果呢

**Comment by ykrank** [comment]
打开安装的这个应用，在里面查看

**Comment by jkl2323** [comment]
这个是必须要打开支付宝的订单详情才能抓取到h5的数据吗  是否可以在支付宝界面 然后收到充值的时候就只能抓取到数据呢 要怎么操作 求大神指教

**Comment by ykrank** [comment]
我这个只是为了试验抓取所有历史账单。实时订单通知属于另外的功能，建议hook对应的通知函数
